/*Cypress.on('uncaught:exception', (err, runnable) => {
    // Hacer algo con la excepción no capturada, por ejemplo, imprimir en la consola
    console.log('Excepción no capturada:', err);
    // Retornar false para evitar que la falla del test sea reportada
    return false;
  });*/
